content:
  - name: pages
    label: Pages
    type: collection
    path: 'content'
    view:
      fields: [ title, published, date ]
    fields:
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text