baseURL = 'https://laetitiajordan.ch'
languageCode = 'fr-ch'
title = 'Laetitia Jordan - Ostéopathe région Morges'
theme = 'laetitia'

[params]
  description = "Ostéopathie pédiatrique, périnatale et générale. Situé à Lavigny, le cabinet est facilement accessible en transports publics depuis Morges, Aubonne, Allaman ou Etoy. Rendez-vous en ligne."
 
 
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
